dist: trusty
language: ruby
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
  - bundle exec rails db:create db:schema:load RAILS_ENV=test
script:
  - bundle exec rspec
